language: csharp
solution: src/kOS.sln

# Pre-shared token for pushing notifications to slack chat
notifications:
  slack: ksp-kos:51DTQ4ZBP9SlGNnLWJ5D84vp

# Before the install the library dlls need to be downloaded
before_install:
- cd Resources
- wget --quiet --user=$KOS_LIB_USER --password=$KOS_LIB_PASSWORD $KOS_LIB_URL -O kos.tar
- tar -xvf kos.tar
- cd ../

# Cleanup the downloaded resources
after_script:
- cd Resources
- rm *.dll
- cd ../
